#  Copyright 2022 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# flake8: noqa


# This file is automatically generated. Please do not modify it directly.
# Find the relevant recipe file in the samples/recipes or samples/ingredients
# directory and apply your changes there.


# [START compute_instances_list_all]
from __future__ import annotations
from google.cloud import compute_v1

def sample_aggregated_list():
    # Create a client
    client = compute_v1.InstancesClient()

    # Initialize request argument(s)
    request = compute_v1.AggregatedListInstancesRequest(
        project="manab-project",
    )

    # Make the request
    page_result = client.aggregated_list(request=request)

    my_instances = {}



    # Handle the response
    for zone, response in page_result:
        if response.instances:
            for i in response.instances:
                print(f"found {i.name} in {zone}")
                my_instances[i.name] = zone
    return my_instances