name: backend_runner
on: push

jobs:
  apply_kustomize:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: testing actions
        run: ls -ltra

      - id: 'auth'
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: ${{ vars.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_FEDERATION }}'
          service_account: ${{ vars.SERVICE_ACCOUNT }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com


      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./GCP
          file: ./GCP/Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/thermal-camera-485502-u2/python-repository/python-cloud:v9

      - name: update the deployment
        run: gcloud run services update python-api --region us-central1 --image us-central1-docker.pkg.dev/thermal-camera-485502-u2/python-repository/python-cloud:v9

